### ISSUE TITLE
RFE: enable use of FORMAT argument in gdc_loadfile

### ISSUE THREAD

**Issue by dheiman** [broadinstitute/gdctools#51]
Looking at [`google.cfg`](https://github.com/broadinstitute/gdctools/blob/master/config/google.cfg), there is a `FORMAT` field in the `loadfile` section set to `firecloud`, but looking at the codebase, this is never consumed, and [`gdc_loadfile`](https://github.com/broadinstitute/gdctools/blob/master/gdctools/gdc_loadfile.py) has no actual code to generate FireCloud loadfiles.

**Comment by noblem** [comment]
This is nominally operational, as of commit https://github.com/broadinstitute/gdctools/commit/df437aba5baf8d4204a45577d4968ba6bf4e15fe
