### ISSUE TITLE
findPython.sh should prioritize an activated virtual environment over all else

### ISSUE THREAD

**Issue by dheiman** [broadinstitute/gdctools#85]
It is unexpected behavior for a 'make install' to install to anywhere other than a virtual environment if one is currently active (via `source <venv dir>/bin/activate.sh`).

Currently, if one is on a Broad server, the virtual environment is overridden, and everything is installed to `/local/firebrowse/latest` or `/xchip/tcga/Tools/gdac/latest`.

While the above behavior is very convenient if a virtual environment is not active, it violates the principle of least surprise when one is, and unnecessarily increases the likelihood of corrupting production tools.

**Comment by noblem** [comment]
This sounds reasonable, and I know that Sam did something like this for at least one other repos (if not more).  Several of our repos have some version or another of this script, and they should in principle all be doing the same thing in the same way.
